CREATE DATABASE bgs;
CREATE DATABASE carstore;
CREATE DATABASE palomar;

GRANT ALL PRIVILEGES ON DATABASE bgs TO admin;
GRANT ALL PRIVILEGES ON DATABASE carstore TO admin;
GRANT ALL PRIVILEGES ON DATABASE palomar TO admin;
